{
 "title": "Scale23x",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Download duration (success)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 7, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, storage_bucket, server_address) (rate(storage_client_operation_duration_seconds{storage_operation_name=\"download\", error_type=\"\"}[1m])))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le, storage_bucket, server_address) (rate(storage_client_operation_duration_seconds{storage_operation_name=\"download\", error_type=\"\"}[1m])))",
     "legendFormat": "p50"
    }
   ]
  },
  {
   "title": "Download duration",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 7, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, storage_bucket, server_address) (rate(storage_client_operation_duration_seconds{storage_operation_name=\"download\"}[1m])))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le, storage_bucket, server_address) (rate(storage_client_operation_duration_seconds{storage_operation_name=\"download\"}[1m])))",
     "legendFormat": "p50"
    }
   ]
  },
  {
   "title": "Download request rate - P95",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 7, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "histogram_count(sum(rate(storage_client_operation_duration_seconds{storage_operation_name=\"download\"}[1m])) by (error_type))",
     "legendFormat": "{{error_type}}"
    }
   ]
  },
  {
   "title": "Upload duration (success codes only)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 7, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, storage_bucket, server_address) (rate(storage_client_operation_duration_seconds{storage_operation_name=\"upload\", error_type=\"\"}[1m])))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le, storage_bucket, server_address) (rate(storage_client_operation_duration_seconds{storage_operation_name=\"upload\", error_type=\"\"}[1m])))",
     "legendFormat": "p50"
    }
   ]
  },
  {
   "title": "Upload duration",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 7, "x": 7, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, storage_bucket, server_address) (rate(storage_client_operation_duration_seconds{storage_operation_name=\"upload\"}[1m])))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le, storage_bucket, server_address) (rate(storage_client_operation_duration_seconds{storage_operation_name=\"upload\"}[1m])))",
     "legendFormat": "p50"
    }
   ]
  },
  {
   "title": "Upload request rate",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 7, "x": 14, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "histogram_count(sum(rate(storage_client_operation_duration_seconds{storage_operation_name=\"upload\"}[1m])) by (error_type))",
     "legendFormat": "{{error_type}}"
    }
   ]
  },
  {
   "title": "Upload duration (success) - P50",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 7, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le, storage_bucket, server_address) (rate(storage_client_operation_duration_seconds{storage_operation_name=\"upload\", error_type=\"\"}[1m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Upload duration ",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 7, "x": 7, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le, storage_bucket, server_address) (rate(storage_client_operation_duration_seconds{storage_operation_name=\"upload\"}[1m])))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}